# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QCheckBox, QComboBox,
    QFrame, QGroupBox, QHeaderView, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QSpinBox, QStatusBar, QTableWidget,
    QTableWidgetItem, QTextEdit, QToolButton, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1139, 496)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(780, 450))
        MainWindow.setMaximumSize(QSize(10000, 10000))
        MainWindow.setContextMenuPolicy(Qt.NoContextMenu)
        icon = QIcon()
        iconThemeName = u"accessories-text-editor"
        if QIcon.hasThemeIcon(iconThemeName):
            icon = QIcon.fromTheme(iconThemeName)
        else:
            icon.addFile(u".", QSize(), QIcon.Normal, QIcon.Off)

        MainWindow.setWindowIcon(icon)
        MainWindow.setInputMethodHints(Qt.ImhLatinOnly)
        MainWindow.setToolButtonStyle(Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setDockOptions(QMainWindow.AnimatedDocks)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.button_delver = QPushButton(self.centralwidget)
        self.button_delver.setObjectName(u"button_delver")
        self.button_delver.setGeometry(QRect(530, 70, 121, 31))
        self.button_delver.setCursor(QCursor(Qt.PointingHandCursor))
        self.weight = QFrame(self.centralwidget)
        self.weight.setObjectName(u"weight")
        self.weight.setGeometry(QRect(700, 20, 71, 51))
        self.weight.setFrameShape(QFrame.StyledPanel)
        self.weight.setFrameShadow(QFrame.Raised)
        self.spin_dist = QSpinBox(self.weight)
        self.spin_dist.setObjectName(u"spin_dist")
        self.spin_dist.setGeometry(QRect(0, 20, 61, 22))
        self.spin_dist.setMaximum(999)
        self.label_dist = QLabel(self.weight)
        self.label_dist.setObjectName(u"label_dist")
        self.label_dist.setGeometry(QRect(0, 0, 49, 16))
        self.to = QFrame(self.centralwidget)
        self.to.setObjectName(u"to")
        self.to.setGeometry(QRect(530, 10, 161, 61))
        self.to.setFrameShape(QFrame.StyledPanel)
        self.to.setFrameShadow(QFrame.Raised)
        self.label_to = QLabel(self.to)
        self.label_to.setObjectName(u"label_to")
        self.label_to.setGeometry(QRect(0, 10, 49, 16))
        self.combo_to = QComboBox(self.to)
        self.combo_to.addItem("")
        self.combo_to.addItem("")
        self.combo_to.addItem("")
        self.combo_to.addItem("")
        self.combo_to.addItem("")
        self.combo_to.addItem("")
        self.combo_to.addItem("")
        self.combo_to.addItem("")
        self.combo_to.setObjectName(u"combo_to")
        self.combo_to.setGeometry(QRect(120, 30, 31, 21))
        self.combo_to.setCursor(QCursor(Qt.PointingHandCursor))
        self.edit_to = QLineEdit(self.to)
        self.edit_to.setObjectName(u"edit_to")
        self.edit_to.setGeometry(QRect(0, 30, 113, 22))
        self.for_2 = QFrame(self.centralwidget)
        self.for_2.setObjectName(u"for_2")
        self.for_2.setGeometry(QRect(360, 10, 161, 61))
        self.for_2.setFrameShape(QFrame.StyledPanel)
        self.for_2.setFrameShadow(QFrame.Raised)
        self.label_for = QLabel(self.for_2)
        self.label_for.setObjectName(u"label_for")
        self.label_for.setGeometry(QRect(0, 10, 49, 16))
        self.combo_for = QComboBox(self.for_2)
        self.combo_for.addItem("")
        self.combo_for.addItem("")
        self.combo_for.addItem("")
        self.combo_for.addItem("")
        self.combo_for.addItem("")
        self.combo_for.addItem("")
        self.combo_for.addItem("")
        self.combo_for.addItem("")
        self.combo_for.setObjectName(u"combo_for")
        self.combo_for.setGeometry(QRect(120, 30, 31, 21))
        self.combo_for.setCursor(QCursor(Qt.PointingHandCursor))
        self.edit_for = QLineEdit(self.for_2)
        self.edit_for.setObjectName(u"edit_for")
        self.edit_for.setGeometry(QRect(0, 30, 113, 22))
        self.label_commandline = QLabel(self.centralwidget)
        self.label_commandline.setObjectName(u"label_commandline")
        self.label_commandline.setGeometry(QRect(20, 270, 751, 16))
        self.paste = QFrame(self.centralwidget)
        self.paste.setObjectName(u"paste")
        self.paste.setGeometry(QRect(20, 10, 311, 91))
        self.paste.setFrameShape(QFrame.StyledPanel)
        self.paste.setFrameShadow(QFrame.Raised)
        self.label_pastegraph = QLabel(self.paste)
        self.label_pastegraph.setObjectName(u"label_pastegraph")
        self.label_pastegraph.setGeometry(QRect(0, 10, 81, 16))
        self.label_pastegraph.setStyleSheet(u"")
        self.edit_pastegraph = QLineEdit(self.paste)
        self.edit_pastegraph.setObjectName(u"edit_pastegraph")
        self.edit_pastegraph.setGeometry(QRect(0, 30, 301, 22))
        self.button_addgraph = QPushButton(self.paste)
        self.button_addgraph.setObjectName(u"button_addgraph")
        self.button_addgraph.setGeometry(QRect(0, 60, 121, 31))
        self.button_addgraph.setCursor(QCursor(Qt.PointingHandCursor))
        self.button_addgraph.setStyleSheet(u"")
        self.thisgraph = QFrame(self.centralwidget)
        self.thisgraph.setObjectName(u"thisgraph")
        self.thisgraph.setGeometry(QRect(10, 120, 761, 141))
        self.thisgraph.setFrameShape(QFrame.Box)
        self.thisgraph.setFrameShadow(QFrame.Raised)
        self.edit_thisgraph = QTextEdit(self.thisgraph)
        self.edit_thisgraph.setObjectName(u"edit_thisgraph")
        self.edit_thisgraph.setEnabled(True)
        self.edit_thisgraph.setGeometry(QRect(10, 40, 741, 51))
        self.edit_thisgraph.setFrameShape(QFrame.Panel)
        self.edit_thisgraph.setFrameShadow(QFrame.Plain)
        self.edit_thisgraph.setReadOnly(True)
        self.label_thisgraph = QLabel(self.thisgraph)
        self.label_thisgraph.setObjectName(u"label_thisgraph")
        self.label_thisgraph.setGeometry(QRect(10, 10, 81, 16))
        self.check_orient = QCheckBox(self.thisgraph)
        self.check_orient.setObjectName(u"check_orient")
        self.check_orient.setGeometry(QRect(100, 10, 131, 20))
        self.check_orient.setCursor(QCursor(Qt.PointingHandCursor))
        self.check_orient.setChecked(False)
        self.button_cleargraph = QPushButton(self.thisgraph)
        self.button_cleargraph.setObjectName(u"button_cleargraph")
        self.button_cleargraph.setGeometry(QRect(10, 100, 121, 31))
        self.button_cleargraph.setCursor(QCursor(Qt.PointingHandCursor))
        self.button_addver = QPushButton(self.centralwidget)
        self.button_addver.setObjectName(u"button_addver")
        self.button_addver.setGeometry(QRect(360, 70, 121, 31))
        self.button_addver.setCursor(QCursor(Qt.PointingHandCursor))
        self.functions = QGroupBox(self.centralwidget)
        self.functions.setObjectName(u"functions")
        self.functions.setGeometry(QRect(10, 300, 761, 91))
        self.functions.setFlat(True)
        self.functions.setCheckable(False)
        self.check_smej = QCheckBox(self.functions)
        self.check_smej.setObjectName(u"check_smej")
        self.check_smej.setGeometry(QRect(10, 20, 141, 20))
        self.check_smej.setCursor(QCursor(Qt.PointingHandCursor))
        self.check_smej.setChecked(False)
        self.check_dost = QCheckBox(self.functions)
        self.check_dost.setObjectName(u"check_dost")
        self.check_dost.setEnabled(True)
        self.check_dost.setGeometry(QRect(10, 40, 151, 20))
        self.check_dost.setCursor(QCursor(Qt.PointingHandCursor))
        self.check_vzaim = QCheckBox(self.functions)
        self.check_vzaim.setObjectName(u"check_vzaim")
        self.check_vzaim.setEnabled(True)
        self.check_vzaim.setGeometry(QRect(10, 60, 211, 20))
        self.check_vzaim.setCursor(QCursor(Qt.PointingHandCursor))
        self.check_printgraph = QCheckBox(self.functions)
        self.check_printgraph.setObjectName(u"check_printgraph")
        self.check_printgraph.setEnabled(True)
        self.check_printgraph.setGeometry(QRect(230, 20, 121, 20))
        self.check_printgraph.setCursor(QCursor(Qt.PointingHandCursor))
        self.check_minostPrim = QCheckBox(self.functions)
        self.check_minostPrim.setObjectName(u"check_minostPrim")
        self.check_minostPrim.setEnabled(True)
        self.check_minostPrim.setGeometry(QRect(230, 60, 181, 20))
        self.check_minostPrim.setCursor(QCursor(Qt.PointingHandCursor))
        self.check_eiler = QCheckBox(self.functions)
        self.check_eiler.setObjectName(u"check_eiler")
        self.check_eiler.setGeometry(QRect(230, 40, 91, 20))
        self.check_eiler.setCursor(QCursor(Qt.PointingHandCursor))
        self.check_components = QCheckBox(self.functions)
        self.check_components.setObjectName(u"check_components")
        self.check_components.setGeometry(QRect(460, 20, 201, 20))
        self.check_components.setCursor(QCursor(Qt.PointingHandCursor))
        self.check_dekstra = QCheckBox(self.functions)
        self.check_dekstra.setObjectName(u"check_dekstra")
        self.check_dekstra.setEnabled(True)
        self.check_dekstra.setGeometry(QRect(460, 40, 201, 20))
        self.check_dekstra.setCursor(QCursor(Qt.PointingHandCursor))
        self.check_minostKruskal = QCheckBox(self.functions)
        self.check_minostKruskal.setObjectName(u"check_minostKruskal")
        self.check_minostKruskal.setEnabled(False)
        self.check_minostKruskal.setGeometry(QRect(460, 60, 201, 20))
        self.check_minostKruskal.setCursor(QCursor(Qt.PointingHandCursor))
        self.combo_vertices = QComboBox(self.functions)
        self.combo_vertices.setObjectName(u"combo_vertices")
        self.combo_vertices.setEnabled(False)
        self.combo_vertices.setGeometry(QRect(410, 60, 31, 21))
        self.combo_vertices.setCursor(QCursor(Qt.PointingHandCursor))
        self.combo_vertices_2 = QComboBox(self.functions)
        self.combo_vertices_2.setObjectName(u"combo_vertices_2")
        self.combo_vertices_2.setEnabled(False)
        self.combo_vertices_2.setGeometry(QRect(650, 40, 31, 22))
        self.matrix = QFrame(self.centralwidget)
        self.matrix.setObjectName(u"matrix")
        self.matrix.setGeometry(QRect(780, 10, 351, 431))
        self.matrix.setFrameShape(QFrame.Box)
        self.matrix.setFrameShadow(QFrame.Raised)
        self.edit_currentTable = QLineEdit(self.matrix)
        self.edit_currentTable.setObjectName(u"edit_currentTable")
        self.edit_currentTable.setGeometry(QRect(10, 350, 281, 22))
        self.edit_currentTable.setReadOnly(True)
        self.table_main = QTableWidget(self.matrix)
        self.table_main.setObjectName(u"table_main")
        self.table_main.setEnabled(True)
        self.table_main.setGeometry(QRect(10, 10, 331, 331))
        self.table_main.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.table_main.setDragEnabled(True)
        self.button_changeTable = QToolButton(self.matrix)
        self.button_changeTable.setObjectName(u"button_changeTable")
        self.button_changeTable.setGeometry(QRect(310, 400, 31, 21))
        self.edit_eiler = QTextEdit(self.matrix)
        self.edit_eiler.setObjectName(u"edit_eiler")
        self.edit_eiler.setGeometry(QRect(10, 380, 281, 41))
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setEnabled(True)
        self.line.setGeometry(QRect(330, 10, 16, 91))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.button_func = QPushButton(self.centralwidget)
        self.button_func.setObjectName(u"button_func")
        self.button_func.setGeometry(QRect(650, 410, 121, 31))
        self.button_func.setCursor(QCursor(Qt.PointingHandCursor))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1139, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u0420\u0435\u0434\u0430\u043a\u0442\u043e\u0440 \u0433\u0440\u0430\u0444\u043e\u0432", None))
        self.button_delver.setText(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0432\u0435\u0440\u0448\u0438\u043d\u0443", None))
        self.label_dist.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0435\u0441", None))
        self.label_to.setText(QCoreApplication.translate("MainWindow", u"\u0412", None))
        self.combo_to.setItemText(0, QCoreApplication.translate("MainWindow", u"a", None))
        self.combo_to.setItemText(1, QCoreApplication.translate("MainWindow", u"b", None))
        self.combo_to.setItemText(2, QCoreApplication.translate("MainWindow", u"c", None))
        self.combo_to.setItemText(3, QCoreApplication.translate("MainWindow", u"d", None))
        self.combo_to.setItemText(4, QCoreApplication.translate("MainWindow", u"e", None))
        self.combo_to.setItemText(5, QCoreApplication.translate("MainWindow", u"g", None))
        self.combo_to.setItemText(6, QCoreApplication.translate("MainWindow", u"h", None))
        self.combo_to.setItemText(7, QCoreApplication.translate("MainWindow", u"f", None))

        self.label_for.setText(QCoreApplication.translate("MainWindow", u"\u0418\u0437", None))
        self.combo_for.setItemText(0, QCoreApplication.translate("MainWindow", u"a", None))
        self.combo_for.setItemText(1, QCoreApplication.translate("MainWindow", u"b", None))
        self.combo_for.setItemText(2, QCoreApplication.translate("MainWindow", u"c", None))
        self.combo_for.setItemText(3, QCoreApplication.translate("MainWindow", u"d", None))
        self.combo_for.setItemText(4, QCoreApplication.translate("MainWindow", u"e", None))
        self.combo_for.setItemText(5, QCoreApplication.translate("MainWindow", u"g", None))
        self.combo_for.setItemText(6, QCoreApplication.translate("MainWindow", u"h", None))
        self.combo_for.setItemText(7, QCoreApplication.translate("MainWindow", u"f", None))

        self.label_commandline.setText(QCoreApplication.translate("MainWindow", u">> ", None))
        self.label_pastegraph.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0441\u0442\u0430\u0432\u0438\u0442\u044c \u0433\u0440\u0430\u0444", None))
#if QT_CONFIG(whatsthis)
        self.button_addgraph.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.button_addgraph.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0441\u0442\u0430\u0432\u0438\u0442\u044c", None))
        self.edit_thisgraph.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.label_thisgraph.setText(QCoreApplication.translate("MainWindow", u"\u0422\u0435\u043a\u0443\u0449\u0438\u0439 \u0433\u0440\u0430\u0444", None))
        self.check_orient.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0440\u0438\u0435\u043d\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0439", None))
        self.button_cleargraph.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0447\u0438\u0441\u0442\u0438\u0442\u044c", None))
        self.button_addver.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u0432\u0435\u0440\u0448\u0438\u043d\u0443", None))
        self.functions.setTitle(QCoreApplication.translate("MainWindow", u"\u0424\u0443\u043d\u043a\u0446\u0438\u0438", None))
        self.check_smej.setText(QCoreApplication.translate("MainWindow", u"\u041c\u0430\u0442\u0440\u0438\u0446\u0430 \u0441\u043c\u0435\u0436\u043d\u043e\u0441\u0442\u0438", None))
        self.check_dost.setText(QCoreApplication.translate("MainWindow", u"\u041c\u0430\u0442\u0440\u0438\u0446\u0430 \u0434\u043e\u0441\u0442\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438", None))
        self.check_vzaim.setText(QCoreApplication.translate("MainWindow", u"\u041c\u0430\u0442\u0440\u0438\u0446\u0430 \u0432\u0437\u0430\u0438\u043c\u043d\u043e\u0439 \u0434\u043e\u0441\u0442\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438", None))
        self.check_printgraph.setText(QCoreApplication.translate("MainWindow", u"\u041d\u0430\u0440\u0438\u0441\u043e\u0432\u0430\u0442\u044c \u0433\u0440\u0430\u0444", None))
        self.check_minostPrim.setText(QCoreApplication.translate("MainWindow", u"\u041c\u0438\u043d. \u043e\u0441\u0442\u043e\u0432\u043e\u0435 \u0434\u0435\u0440\u0435\u0432\u043e (\u041f\u0440\u0438\u043c)", None))
        self.check_eiler.setText(QCoreApplication.translate("MainWindow", u"\u042d\u0439\u043b\u0435\u0440\u043e\u0432\u043e\u0441\u0442\u044c", None))
        self.check_components.setText(QCoreApplication.translate("MainWindow", u"\u041a\u043e\u043c\u043f\u043e\u043d\u0435\u043d\u0442\u044b \u0441\u0438\u043b\u044c\u043d\u043e\u0439 \u0441\u0432\u044f\u0437\u043d\u043e\u0441\u0442\u0438", None))
        self.check_dekstra.setText(QCoreApplication.translate("MainWindow", u"\u041a\u0440\u0430\u0442\u0447\u0430\u0439\u0448\u0438\u0435 \u043f\u0443\u0442\u0438 \u0438\u0437 \u0432\u0435\u0440\u0448\u0438\u043d\u044b", None))
        self.check_minostKruskal.setText(QCoreApplication.translate("MainWindow", u"\u041c\u0438\u043d. \u043e\u0441\u0442\u043e\u0432\u043d\u043e\u0435 \u0434\u0435\u0440\u0435\u0432\u043e (\u041a\u0440\u0443\u0441\u043a\u0430\u043b)", None))
        self.edit_currentTable.setText("")
#if QT_CONFIG(tooltip)
        self.button_changeTable.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>&gt;</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.button_changeTable.setText(QCoreApplication.translate("MainWindow", u"<->", None))
        self.button_func.setText(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u043f\u043e\u043b\u043d\u0438\u0442\u044c", None))
    # retranslateUi

